default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'root' } %>
  host: webapp_db_1
  
  development:
    <<: *default
    database: webapp_development
    
  test:
    <<: *default
    database: webapp_test
    port: 3306