default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'root' } %>
  port: 3306
  host: <%= ENV['DB_HOST'] %>
  
development:
  <<: *default
  database: webapp_development
    
test:
  <<: *default
  database: webapp_test