default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_ROOT_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_ROOT_PASSWORD') { 'root' } %>
  host: db

development:
  <<: *default
  database: webapp_development
  host: db
  
test:
  <<: *default
  database: webapp_test
  host: db